### ISSUE TITLE
Updating target instance info fails on targets with more than 64KB of seeds

### ISSUE THREAD

**Issue by jmvezic** [WebCuratorTool/webcurator-v2-legacy#136]
If you provide a list of seeds (via import feature) which exceeds 64KB (even less, considering they get expanded into XML), the target instance is always stuck in "scheduled", since the database can't be updated.

The underlying cause is that table SIP_PART_ELEMENT, column SPE_VALUE is of type "text", which maxes out at 64KB. The field should be altered to either "mediumtext" (16MB) or "longtext" (4GB). Mediumtext seems like a solid option.

**Comment by jmvezic** [comment]
Made a PR that fixes this: https://github.com/DIA-NZ/webcurator/pull/137

**Comment by hannakoppelaar** [comment]
@jmvezic Thanks for pointing this out. Current development of WCT has moved to https://github.com/WebCuratorTool/webcurator. I've created a PR there. Note that the PostgreSQL text type is large enough. This issue only affect MySQL.

**Comment by obrienben** [comment]
Fixed in https://github.com/WebCuratorTool/webcurator repo
